### Create product
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "Blue Raspberry Lollipop Bag",
  "price": 159,
  "stock": 100,
  "category": "Jelly",
  "imageUrl": "https://res.cloudinary.com/dcwlgjz6z/image/upload/v1768922766/Cotton_Candy_Lollipop_Bag_asy4vc.png"
}

### Delete Product Test
DELETE http://localhost:3000/api/products/697045695656ead08646bc0f

### GET product
GET http://localhost:3000/api/products
Content-Type: application/json