### Create product
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "XmasSetL",
  "price": 359,
  "stock": 100,
  "category": "specialset",
  "imageUrl": "https://res.cloudinary.com/dcwlgjz6z/image/upload/v1768924851/XmasSetL_mrfcgw.png"
}

### Delete Product Test
DELETE http://localhost:3000/api/products/697045695656ead08646bc0f

### GET product
GET http://localhost:3000/api/products
Content-Type: application/json