// Test of PRODUCT_ID = 696897940f34cb9f5d50c48f

### View popularity
PUT http://localhost:3000/api/products/69719f093ffda758d34e9408/popular
Content-Type: application/json

{
  "type": "VIEW"
}


### ADD_TO_CART popularity
PUT http://localhost:3000/api/products/69719f093ffda758d34e9408/popular
Content-Type: application/json

{
  "type": "ADD_TO_CART"
}


### ORDER_SUCCESS popularity
PUT http://localhost:3000/api/products/69719b9f3ffda758d34e93ef/popular
Content-Type: application/json

{
  "type": "ORDER_SUCCESS"
}


### INVALID TYPE TEST
PUT http://localhost:3000/api/products/69719f093ffda758d34e9408f/popular
Content-Type: application/json

{
  "type": "LIKE"
}
