### users test
GET http://localhost:3000/api/users

### Create User Test
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "test6",
    "email": "test6@example.com",
    "password": "test6",
    "first_name": "test6",
    "last_name": "test6",
    "address": "test6",
    "role": "USER"
}

### Get User by ID Test
DELETE http://localhost:3000/api/users/696bc23131cc181ac0e8bef6


### Update User Test
PUT http://localhost:3000/api/users/696bc23131cc181ac0e8bef6
Content-Type: application/json

{
    "address": "test6-updated"
}

### Login Test
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "test6@example.com",
    "password": "test6"
}

### Logout Test
POST http://localhost:3000/api/users/logout

### products test
GET http://localhost:3000/api/products

### Create Product Test
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "Test Barbara1",
    "description": "Delicious barbara1 chocolate",
    "price": 5.99,
    "stock": 50,
    "category": "chocolate"
}

### Get Product by ID Test
GET http://localhost:3000/api/products/696e7878dc53bb780fcc29b7

### Update Product Test
PUT http://localhost:3000/api/products/696e7878dc53bb780fcc29b7
Content-Type: application/json

{
    "price": 6.49,
    "stock": 60
}

### Delete Product Test
DELETE http://localhost:3000/api/products/696e7794fbab4b8cfd05c370

### cart test
GET http://localhost:3000/api/cart/

### Add to Cart Test
POST http://localhost:3000/api/cart/items
Content-Type: application/json

{
    "productId": "696e7878dc53bb780fcc29b7",
    "quantity": 7
}

### Delete Cart Test
DELETE http://localhost:3000/api/cart/696de6a2508df3c219d325b9

### Delete Cart Item Test
DELETE http://localhost:3000/api/cart/items/696ea1f4d3f

### category test
GET http://localhost:3000/api/products/categories

### Create Category Test
POST http://localhost:3000/api/products/categories
Content-Type: application/json

{
    "name": "Chocolate",
    "description": "Tasty chocolate candies"
}

### GET Category Test
PUT http://localhost:3000/api/products/categories/696e7268a620c20e72c2b998
Content-Type: application/json

{
    "description": "Delicious gummy candies"
}

### Delete Category Test
DELETE http://localhost:3000/api/products/categories/696e7268a620c20e72c2b998

### Category Filter Test
GET http://localhost:3000/api/products?category=CHOCOLATE

### GET Popular Products
GET http://localhost:3000/api/products/popular

### Create Order Test
POST http://localhost:3000/api/orders
Content-Type: application/json

{
    "items": [
        {
            "product_id": "696e7878dc53bb780fcc29b7",
            "quantity": 1
        }
    ]
}

### Get Orders Test
GET http://localhost:3000/api/orders

### Get Order by ID Test
GET http://localhost:3000/api/orders/696ef62e9904ee9e9b078c03

### Update Order Test
PUT http://localhost:3000/api/orders/696ef62e9904ee9e
Content-Type: application/json

{
    "status": "COMPLETED"
}

### Delete Order Test
DELETE http://localhost:3000/api/orders/696f1ea1ce5aef6cfff46a9b
Authorization: Bearer {{token}}

### User Profile Test
GET http://localhost:3000/api/users/me

### --------------------------------------------------------------

# @name login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "test6@example.com",
    "password": "test6"
}

### บรรทัดนี้คือการดึง Token มาเก็บไว้ในตัวแปรชื่อ 'token'
@token = {{login.response.body.token}}

### -------------------------------------------

### ทดสอบดึงข้อมูล Profile (จะใช้ Token อัตโนมัติจากด้านบน)
GET http://localhost:3000/api/users/me
Authorization: Bearer {{token}}

### -------------------------------------------

### ทดสอบดึง Order ของตัวเอง
GET http://localhost:3000/api/orders/my-orders
Authorization: Bearer {{token}}

### ---------------------------------------------------------

### Create Order Test
POST http://localhost:3000/api/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "items": [
        {
            "product_id": "696e7878dc53bb780fcc29b7",
            "quantity": 1
        }
    ]
}

### 2. เทส Delete Order (ห้ามมีบรรทัดว่างระหว่าง DELETE กับ Authorization)
DELETE http://localhost:3000/api/orders/696f2263036b93a283bda809
Authorization: Bearer {{token}}

### create address
POST http://localhost:3000/api/users/address
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NjhhNWEyN2RjOTBhMzU3YzM1Y2ZiOSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzY4OTMxOTU3LCJleHAiOjE3Njk1MzY3NTd9.g_RKmlidxoXklfmx_MOPQ-R5QKu8yiYrmyQ6ftG5zHA
Content-Type: application/json

{
  "address": "123 ถนนสุขุมวิท กรุงเทพ"
}

### update address
PUT http://localhost:3000/api/users/address
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NjhhNWEyN2RjOTBhMzU3YzM1Y2ZiOSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzY4OTMxOTU3LCJleHAiOjE3Njk1MzY3NTd9.g_RKmlidxoXklfmx_MOPQ-R5QKu8yiYrmyQ6ftG5zHA
Content-Type: application/json

{
  "address": "456 ถนนพหลโยธิน กรุงเทพ"
}


### delete address
DELETE http://localhost:3000/api/users/address
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NjhhNWEyN2RjOTBhMzU3YzM1Y2ZiOSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzY4OTMxOTU3LCJleHAiOjE3Njk1MzY3NTd9.g_RKmlidxoXklfmx_MOPQ-R5QKu8yiYrmyQ6ftG5zHA
Content-Type: application/json