GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "test5",
    "email": "test5@example.com",
    "password": "test5",
    "first_name": "test5",
    "last_name": "test5",
    "address": "test5",
    "role": "USER"

}

###
GET http://localhost:3000/api/products

### create address
POST http://localhost:3000/api/users/address
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NjhhNWEyN2RjOTBhMzU3YzM1Y2ZiOSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzY4OTMxOTU3LCJleHAiOjE3Njk1MzY3NTd9.g_RKmlidxoXklfmx_MOPQ-R5QKu8yiYrmyQ6ftG5zHA
Content-Type: application/json

{
  "address": "123 ถนนสุขุมวิท กรุงเทพ"
}

### update address
PUT http://localhost:3000/api/users/address
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NjhhNWEyN2RjOTBhMzU3YzM1Y2ZiOSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzY4OTMxOTU3LCJleHAiOjE3Njk1MzY3NTd9.g_RKmlidxoXklfmx_MOPQ-R5QKu8yiYrmyQ6ftG5zHA
Content-Type: application/json

{
  "address": "456 ถนนพหลโยธิน กรุงเทพ"
}


### delete address
DELETE http://localhost:3000/api/users/address
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NjhhNWEyN2RjOTBhMzU3YzM1Y2ZiOSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzY4OTMxOTU3LCJleHAiOjE3Njk1MzY3NTd9.g_RKmlidxoXklfmx_MOPQ-R5QKu8yiYrmyQ6ftG5zHA
Content-Type: application/json