GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "test5",
    "email": "test5@example.com",
    "password": "test5",
    "first_name": "test5",
    "last_name": "test5",
    "address": "test5",
    "role": "USER"

}

###
GET http://localhost:3000/api/products